apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlflow-k8s
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow-image
          image: MLFLOW_DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name:  BACKEND_URI
              value: "sqlite:////mlflow/mlflow.db"
            - name:  ARTIFACT_ROOT
              value: "/mlflow/artifacts"
            - name:  NUMBER_OF_GC
              value: "4"
            - name: BACK_END_PORT
              value: "8001"
              